/** Browser-mode twin of backend/app/routers/files.py: generates the same
 * products CSV and minimal hand-built PDF, and validates uploads. */

import type { UploadEcho } from '@/api/types'
import { EngineError } from '@/engine/errors'
import { db } from '@/engine/store'

export const MAX_UPLOAD_BYTES = 1024 * 1024 // 1 MB

/** RFC-4180-ish escaping: quote fields containing commas, quotes or newlines. */
function csvField(value: string | number): string {
  const text = String(value)
  return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text
}

export function productsCsv(): string {
  const rows = [['id', 'name', 'price', 'category', 'stock'].join(',')]
  for (const product of db.products) {
    rows.push(
      [product.id, product.name, product.price, product.category, product.stock]
        .map(csvField)
        .join(','),
    )
  }
  return `${rows.join('\n')}\n`
}

/** A tiny valid single-page PDF generated by hand (ported from the FastAPI
 * router). All content is ASCII, so string offsets equal byte offsets. */
export function sampleReportPdf(): Uint8Array {
  const stream = 'BT /F1 24 Tf 72 720 Td (TAW Sample Report - download works!) Tj ET'
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R ' +
      '/Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ]
  let out = '%PDF-1.4\n'
  const offsets: number[] = []
  objects.forEach((body, index) => {
    offsets.push(out.length)
    out += `${index + 1} 0 obj\n${body}\nendobj\n`
  })
  const xrefAt = out.length
  out += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (const offset of offsets) {
    out += `${String(offset).padStart(10, '0')} 00000 n \n`
  }
  out += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF\n`
  return new TextEncoder().encode(out)
}

/** Validates the multipart file part and echoes its metadata (same contract
 * as POST /api/files/upload on the FastAPI side). */
export function echoUpload(file: File | null): UploadEcho {
  if (!file) {
    throw new EngineError(400, 'VALIDATION_ERROR', 'No file part in the upload.')
  }
  if (file.size > MAX_UPLOAD_BYTES) {
    throw new EngineError(400, 'VALIDATION_ERROR', 'File is larger than the 1 MB limit.')
  }
  return {
    fileName: file.name,
    sizeBytes: file.size,
    contentType: file.type || 'application/octet-stream',
  }
}
