import csv
import io

from fastapi import APIRouter, Request, Response, UploadFile

from app.core.errors import ApiError
from app.store.memory import MemoryStore

router = APIRouter(prefix="/api/files", tags=["files"])

MAX_UPLOAD_BYTES = 1024 * 1024  # 1 MB


def _store(request: Request) -> MemoryStore:
    return request.app.state.store


@router.get("/products.csv")
def download_products_csv(request: Request) -> Response:
    store = _store(request)
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(["id", "name", "price", "category", "stock"])
    for product in store.products.values():
        writer.writerow([product["id"], product["name"], product["price"], product["category"], product["stock"]])
    return Response(
        content=buffer.getvalue(),
        media_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="products.csv"'},
    )


def _minimal_pdf(text: str) -> bytes:
    """A tiny valid single-page PDF generated by hand (no external deps)."""
    stream = f"BT /F1 24 Tf 72 720 Td ({text}) Tj ET".encode()
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R "
        b"/Resources << /Font << /F1 5 0 R >> >> >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out = io.BytesIO()
    out.write(b"%PDF-1.4\n")
    offsets = []
    for index, body in enumerate(objects, start=1):
        offsets.append(out.tell())
        out.write(f"{index} 0 obj\n".encode() + body + b"\nendobj\n")
    xref_at = out.tell()
    out.write(f"xref\n0 {len(objects) + 1}\n".encode())
    out.write(b"0000000000 65535 f \n")
    for offset in offsets:
        out.write(f"{offset:010d} 00000 n \n".encode())
    out.write(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF\n".encode()
    )
    return out.getvalue()


@router.get("/sample-report.pdf")
def download_sample_pdf() -> Response:
    return Response(
        content=_minimal_pdf("TAW Sample Report - download works!"),
        media_type="application/pdf",
        headers={"Content-Disposition": 'attachment; filename="sample-report.pdf"'},
    )


@router.post("/upload", status_code=201)
async def upload_file(file: UploadFile) -> dict:
    content = await file.read()
    if len(content) > MAX_UPLOAD_BYTES:
        raise ApiError(400, "VALIDATION_ERROR", "File is larger than the 1 MB limit.")
    return {
        "fileName": file.filename,
        "sizeBytes": len(content),
        "contentType": file.content_type,
    }
